version: "3"
services:
  queen:
    build:
      context: .
    restart: always
    image: "seacreeper/queen:latest"
    container_name: seacreeper-queen
    networks:
      - seacreeper
    ports:
      - "8080:8080/tcp"
    volumes:
      - queen_volume:/app/volume

networks:
  seacreeper:

volumes:
  queen_volume: